const DRAFT_KEY='manga-us-drafts-v1';
let lessonDrafts={};try{lessonDrafts=JSON.parse(localStorage.getItem(DRAFT_KEY)||'{}')}catch{lessonDrafts={}}
let restoringDraft=false;
const uxBaseControl=v2Control;
v2Control=function(type,index){
  if(type==='chart')return '<canvas id="storyChart" width="760" height="280"></canvas><fieldset class="plain-picks"><legend>只根据图上已经发生的事，哪句最稳妥？</legend><label><input type="radio" name="basicChartRead" value="wait">价格正在走强，但还要等收盘或回踩确认</label><label><input type="radio" name="basicChartRead" value="chase">最后一根是绿色，所以现在满仓追入</label><label><input type="radio" name="basicChartRead" value="certain">量柱变高，说明明天一定上涨</label></fieldset><div class="chart-actions"><button data-run>提交我的观察</button></div>';
  if(index===22)return '<div class="number-task"><p>Vega 0.12，IV 下降 10 个百分点；忽略其他因素，一张标准合约价值约变化多少美元？</p><label>合约价值变化<input id="vegaAnswer" type="number" step="1"></label></div><button data-run>核对 Vega</button>';
  if(type==='final')return '<div class="final-fields"><label>行情状态<input id="planState"></label><label>交易方向<select id="planSide"><option value="">请选择</option><option value="long">做多：上涨获利</option><option value="short">做空：下跌获利</option></select></label><label>入场价<input id="planEntry" type="number"></label><label>止损价<input id="planStop" type="number"></label><label>股数<input id="planShares" type="number"></label><label>每股多付的价差和费用<input id="planCost" type="number" step="0.01"></label><label>按计划止损会亏多少<input id="planLoss" type="number"></label><label>假设隔夜突然跌或涨（%）<input id="planGapPct" type="number" step="0.1"></label><label>按这个跳空幅度会亏多少<input id="planGapLoss" type="number"></label><label>出现什么说明判断错了<input id="planInvalid"></label><label>订单计划<input id="planOrder"></label><label>可能一起亏钱的持仓组<input id="planCluster"></label><label>这组其他持仓在同一情景下会亏多少<input id="planClusterLoss" type="number" min="0" value="0"></label><label>隔夜突然跳价时怎么处理<input id="planGap"></label><label>事件风险<input id="planEvent"></label><label>复盘时间<input id="planReview" type="datetime-local"></label></div><p>先取这笔交易“按计划止损的损失”和“按假设跳空幅度计算的损失”中较大的一个，再加上这组其他持仓在同一情景下会亏多少。合计必须不超过当前净值的 2%。做多的止损应低于入场价，做空的止损应高于入场价。</p><button data-run>检查整份计划</button>';
  return uxBaseControl(type,index);
};
const uxBaseValidate=v3Validate;
v3Validate=function(type){
  if(type==='chart')return document.querySelector('input[name="basicChartRead"]:checked')?.value==='wait';
  if(v2Active===22)return +vegaAnswer.value===-120;
  if(type==='final'){const side=planSide.value,entry=+planEntry.value,stop=+planStop.value,shares=+planShares.value,cost=+planCost.value,gap=+planGapPct.value,clusterLoss=+planClusterLoss.value,planned=(Math.abs(entry-stop)+cost)*shares,gapLoss=(entry*gap/100+cost)*shares,directionOk=side==='long'?stop<entry:side==='short'?stop>entry:false,totalRisk=clusterLoss+Math.max(planned,gapLoss);return v2Done.size>=27&&directionOk&&entry>0&&stop>0&&shares>0&&cost>=0&&gap>0&&clusterLoss>=0&&Math.abs(planned-(+planLoss.value))<.01&&Math.abs(gapLoss-(+planGapLoss.value))<.01&&totalRisk<=sim.account.equity*.02&&['planState','planInvalid','planOrder','planCluster','planGap','planEvent','planReview'].every(id=>document.querySelector('#'+id).value.trim().length>=4)}
  if(v2Active===26){const age=gateTime.value?(Date.now()-new Date(gateTime.value))/36e5:999;return /^https:\/\/(www\.)?(sec\.gov|federalreserve\.gov|bls\.gov|home\.treasury\.gov)\//i.test(gateSource.value)&&age>=0&&age<=24&&gateBear.value.trim().length>=8&&+gateLoss.value>0&&+gateLoss.value<=sim.account.equity*.02&&gateInvalid.value.trim().length>=8}
  return uxBaseValidate(type);
};
function lessonHeadingFocus(){const h=lessonStage.querySelector('h2');if(h){h.tabIndex=-1;h.focus({preventScroll:true});lessonStage.scrollIntoView({block:'start'})}}
function persistDraft(){if(restoringDraft)return;const draft={};lessonStage.querySelectorAll('input,select,textarea').forEach((el,i)=>{const key=el.id||`${el.type}-${i}`;draft[key]=el.type==='checkbox'||el.type==='radio'?el.checked:el.value});lessonDrafts[v2Active]=draft;localStorage.setItem(DRAFT_KEY,JSON.stringify(lessonDrafts))}
function restoreDraft(){const draft=lessonDrafts[v2Active]||{};restoringDraft=true;try{lessonStage.querySelectorAll('input,select,textarea').forEach((el,i)=>{const key=el.id||`${el.type}-${i}`;if(!(key in draft))return;const value=el.type==='checkbox'||el.type==='radio'?!!draft[key]:String(draft[key]);if(el.type==='checkbox'||el.type==='radio'){if(el.checked===value)return;el.checked=value}else{if(el.value===value)return;el.value=value}el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}))})}finally{restoringDraft=false}}
function chartTable(){const host=document.querySelector('#chartDataText');if(!host)return;const rows=SIM_BARS.slice(0,replayCount());host.innerHTML=`<details class="chart-data"><summary>用文字读取当前 K 线数据</summary><table><thead><tr><th>交易日</th><th>开盘价</th><th>最高价</th><th>最低价</th><th>收盘价</th><th>成交量</th></tr></thead><tbody>${rows.map((b,i)=>`<tr><td>D${i+1}</td>${b.map(v=>`<td>${v}</td>`).join('')}</tr>`).join('')}</tbody></table></details>`}
const uxBaseRender=v2Render;
v2Render=function(){uxBaseRender();restoreDraft();lessonStage.querySelectorAll('input,select,textarea').forEach(el=>el.addEventListener('input',persistDraft));const feedback=document.querySelector('#lessonFeedback');if(feedback){feedback.setAttribute('role','status');feedback.setAttribute('aria-live','polite')}const chart=document.querySelector('#storyChart');if(chart){chart.setAttribute('role','img');chart.setAttribute('aria-label','SHAN 教学 K 线与成交量图，文字数据表位于图后');chart.insertAdjacentHTML('afterend','<div id="chartDataText"></div>');chartTable();const reveal=document.querySelector('#revealBar');if(reveal){const old=reveal.onclick;reveal.onclick=e=>{old(e);chartTable()}}}stageRail.querySelectorAll('[data-v2]').forEach(button=>{button.toggleAttribute('aria-current',+button.dataset.v2===v2Active);button.setAttribute('aria-label',`第 ${+button.dataset.v2+1} 章 ${button.textContent.trim()}${button.classList.contains('done')?'，已通过':''}`);button.onclick=()=>{persistDraft();v2Active=+button.dataset.v2;v2Save();v2Render();lessonHeadingFocus()}});const prev=lessonStage.querySelector('[data-prev]'),next=lessonStage.querySelector('[data-next]');if(prev)prev.onclick=()=>{persistDraft();v2Active--;v2Save();v2Render();lessonHeadingFocus()};if(next)next.onclick=()=>{persistDraft();v2Active++;v2Save();v2Render();lessonHeadingFocus()};const proof=tradeJournal.querySelector('.proof');if(proof){proof.setAttribute('role','progressbar');proof.setAttribute('aria-label','课程进度');proof.setAttribute('aria-valuemin','0');proof.setAttribute('aria-valuemax','28');proof.setAttribute('aria-valuenow',String(v2Done.size))}};
document.querySelectorAll('[data-complete]').forEach(button=>{button.textContent='开始 28 章交易训练';button.onclick=()=>document.querySelector('#trainingDesk').scrollIntoView({behavior:'smooth'})});
v2Render();
