const mastery=document.createElement('section');mastery.id='mastery';mastery.className='module';mastery.innerHTML=`
<div class="section-head"><div><span class="kicker">专业验收台</span><h2>不是看完，是交出五份证据</h2></div><span class="tag danger">五域 ≥ 80% 才结业</span></div>
<div class="mastery-grid">
<article><h3>收益率 / 久期</h3><p>债券价格近似变化 = -久期 × 收益率变化。</p><label>久期<input id="duration" type="number" value="8" step="0.5"></label><label>收益率变化（bp）<input id="bps" type="number" value="50"></label><button id="calcBond">计算</button><b id="bondResult">等待计算</b></article>
<article><h3>Greeks / IV</h3><p>财报前 Call：Delta 0.55、Vega 0.12、Theta -0.08。股价不变，IV 下跌 20 点，过 1 天。</p><div class="mini-quiz" data-right="2"><button>约 +$2.48</button><button>不变</button><button>约 -$2.48</button></div><b class="mini-feedback">先计算 Vega 与 Theta 影响。</b></article>
<article><h3>TradingAgents 风险门</h3><label>数据时间戳<input id="agentTime" type="datetime-local"></label><label>看多理由<textarea id="bullCase"></textarea></label><label>反证 / 看空理由<textarea id="bearCase"></textarea></label><label>最大损失（美元）<input id="maxLoss" type="number"></label><label>失效条件<textarea id="invalidCase"></textarea></label><button id="runAgents">提交风险官</button><b id="agentVerdict">等待研究卡</b></article>
</div>
<div class="final-exam"><h3>五域结业考试</h3><p>每题对应一个能力域。4/5 才通过；错题会保留，不因点击按钮消失。</p><div id="examQuestions"></div><button id="submitExam">提交结业验收</button><div id="examResult" class="lab-output">尚未提交</div></div>
<div class="sources"><b>资料与数据边界</b><a href="https://www.federalreserve.gov/monetarypolicy.htm" target="_blank" rel="noreferrer">Federal Reserve · FOMC</a><a href="https://home.treasury.gov/resource-center/data-chart-center/interest-rates/TextView?type=daily_treasury_yield_curve" target="_blank" rel="noreferrer">U.S. Treasury · Yield Curve</a><a href="https://www.optionseducation.org/videolibrary/probability-ii-standard-deviations-and-tail-risk" target="_blank" rel="noreferrer">OIC · Tail Risk Video</a><a href="https://github.com/TauricResearch/TradingAgents" target="_blank" rel="noreferrer">TradingAgents · GitHub</a><small>K 线为教学构造样本，不冒充实时行情。使用真实交易前，必须重新获取带时间戳的 OHLCV。</small></div>`;document.querySelector('footer').before(mastery);
const quantLab=document.createElement('section');quantLab.className='module';quantLab.innerHTML=`<div class="section-head"><div><span class="kicker">数据回测 · 组合压力</span><h2>收益不是成绩单，回撤和样本外才是</h2></div><span class="tag">含成本 · 分样本</span></div><div class="quant-grid"><article><h3>趋势策略教学回测</h3><label>每次交易成本（bp）<input id="tradeCost" type="number" value="10"></label><label>数据区间<select id="sampleSet"><option value="train">训练样本</option><option value="test">样本外</option></select></label><button id="runBacktest">运行回测</button><div id="backtestResult" class="lab-output"></div><canvas id="equityChart" width="700" height="260"></canvas></article><article><h3>多资产压力测试</h3><p>股票 60%、长债 20%、短债 10%、现金 10%。</p><label>情景<select id="shock"><option value="inflation">通胀再起：股 -12%，长债 -10%</option><option value="recession">衰退：股 -20%，长债 +8%</option><option value="liquidity">流动性冲击：股 -18%，长债 -6%</option></select></label><button id="runAssets">运行组合压力</button><div id="assetResult" class="lab-output"></div></article></div>`;mastery.before(quantLab);
const train=[100,102,101,105,108,106,111,114,110,116,119,117,123],test=[100,98,101,97,95,99,96,103,101,100,106,104,108];runBacktest.onclick=()=>{const data=sampleSet.value==='train'?train:test,cost=+tradeCost.value/10000;let eq=100,peak=100,dd=0,trades=0,curve=[eq];for(let i=2;i<data.length;i++){if(data[i-1]>data[i-2]){eq*=1+(data[i]/data[i-1]-1)-cost;trades++}peak=Math.max(peak,eq);dd=Math.min(dd,eq/peak-1);curve.push(eq)}backtestResult.textContent=`净值 ${eq.toFixed(1)}；最大回撤 ${(dd*100).toFixed(1)}%；交易 ${trades} 次。${sampleSet.value==='test'?'这是样本外结果，仍不代表未来。':'训练样本好看不算过关，切到样本外再看。'}`;const c=equityChart,x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);x.beginPath();curve.forEach((v,i)=>{const px=25+i/(curve.length-1)*(c.width-50),py=c.height-25-(v-85)/40*(c.height-50);i?x.lineTo(px,py):x.moveTo(px,py)});x.strokeStyle='#3b8b61';x.lineWidth=3;x.stroke()};runAssets.onclick=()=>{const losses={inflation:-.092,recession:-.104,liquidity:-.12},r=losses[shock.value];assetResult.textContent=`组合压力损失约 ${(r*100).toFixed(1)}%。若账户熔断线为 8%，本情景全部触发：停止加风险，检查再平衡与现金缓冲。`};
calcBond.onclick=()=>{const change=-(+duration.value)*(+bps.value/100);bondResult.textContent=`价格近似变化 ${change.toFixed(2)}%。这是线性近似，大幅变动还需考虑凸性。`};
document.querySelectorAll('.mini-quiz button').forEach((b,i)=>b.onclick=()=>{const ok=i===2;b.parentElement.querySelectorAll('button').forEach((x,n)=>x.className=n===2?'correct':n===i?'wrong':'');b.parentElement.nextElementSibling.textContent=ok?'通过：Vega 约 -$2.40，Theta 约 -$0.08，总计约 -$2.48。':'未通过：方向不变不代表期权价格不变；计算 Vega 与 Theta。'});
runAgents.onclick=()=>{const age=agentTime.value?(Date.now()-new Date(agentTime.value).getTime())/36e5:9999;let reasons=[];if(age>24)reasons.push('数据超过24小时或缺时间戳');if(bullCase.value.trim().length<20)reasons.push('看多证据不足');if(bearCase.value.trim().length<20)reasons.push('缺反证');if(+maxLoss.value<=0)reasons.push('未声明最大损失');if(invalidCase.value.trim().length<15)reasons.push('失效条件不足');agentVerdict.textContent=reasons.length?`风险官拒绝：${reasons.join('；')}。`:`风险官允许进入 Paper：run-${Date.now().toString(36)}。仍不允许自动实盘。`};
const exam=[['K线','突破最可靠的组合？',['盘中刺穿','放量收盘站稳且回踩守住','社媒热度'],1],['仓位','同一风险簇三仓同时下跌，应按什么管理？',['三笔独立机会','组合暴露与共同压力','只看最大盈利'],1],['宏观','FOMC前最重要的准备？',['满仓猜方向','三情景与失效条件','忽略2Y收益率'],1],['期权','买Call财报后方向对仍亏的常见原因？',['IV Crush与Theta','成交量颜色','股票代码'],0],['Agents','研究卡缺反证时风险官应？',['继续下单','拒绝进入Paper','放大仓位'],1]];examQuestions.innerHTML=exam.map((q,i)=>`<fieldset><legend>${i+1}. ${q[0]}：${q[1]}</legend>${q[2].map((o,n)=>`<label><input type="radio" name="exam-${i}" value="${n}">${o}</label>`).join('')}</fieldset>`).join('');submitExam.onclick=()=>{let score=0,missing=0;exam.forEach((q,i)=>{const x=document.querySelector(`input[name="exam-${i}"]:checked`);if(!x)missing++;else if(+x.value===q[3])score++});if(missing){examResult.textContent=`还有 ${missing} 题未答。`;return}const pass=score>=4;examResult.textContent=`${score}/5 · ${pass?'结业验收通过。请继续用 Paper 记录至少 20 笔再评估真实行为。':'未通过。回到对应章节复习，不能用收益结果替代决策质量。'}`;localStorage.setItem('manga-us-final',pass?'pass':'review')};
