const mastery=document.createElement('section');mastery.id='mastery';mastery.className='module';mastery.innerHTML=`
<div class="section-head"><div><span class="kicker">学习检查台</span><h2>做五类练习，看看自己是否会用</h2></div><span class="tag danger">五类练习 · 至少答对 80%</span></div>
<div class="mastery-grid">
<article><h3>利率变了，债券价格会怎样</h3><p>债券价格近似变化 = -久期 × 收益率变化。</p><label>久期（衡量债券价格对利率的敏感度）<input id="duration" type="number" value="8" step="0.5"></label><label>收益率变化（基点，100 基点 = 1 个百分点）<input id="bps" type="number" value="50"></label><button id="calcBond">计算</button><b id="bondResult">等待计算</b></article>
<article><h3>期权：时间和波动率怎样影响价格</h3><p>财报前 Call：Delta 0.55、Vega 0.12、Theta -0.08。股价不变，IV 下跌 20 点，过 1 天。</p><div class="mini-quiz" data-right="2"><button>约 +$2.48</button><button>不变</button><button>约 -$2.48</button></div><b class="mini-feedback">先计算 Vega 与 Theta 影响。</b></article>
<article><h3>TradingAgents 风险门</h3><label>数据对应的日期和时间<input id="agentTime" type="datetime-local"></label><label>看多理由<textarea id="bullCase"></textarea></label><label>哪些证据说明可能下跌<textarea id="bearCase"></textarea></label><label>最大损失（美元）<input id="maxLoss" type="number"></label><label>出现什么情况就放弃原判断<textarea id="invalidCase"></textarea></label><button id="runAgents">提交风险官</button><b id="agentVerdict">等待研究卡</b></article>
</div>
<div class="final-exam"><h3>五类知识结业检查</h3><p>每题检查一类知识。4/5 才通过；错题会保留，不因点击按钮消失。</p><div id="examQuestions"></div><button id="submitExam">提交结业验收</button><div id="examResult" class="lab-output">尚未提交</div></div>
<div class="sources"><b>资料来源与使用限制</b><a href="https://www.federalreserve.gov/monetarypolicy.htm" target="_blank" rel="noreferrer">Federal Reserve · FOMC</a><a href="https://home.treasury.gov/resource-center/data-chart-center/interest-rates/TextView?type=daily_treasury_yield_curve" target="_blank" rel="noreferrer">U.S. Treasury · Yield Curve</a><a href="https://www.optionseducation.org/videolibrary/probability-ii-standard-deviations-and-tail-risk" target="_blank" rel="noreferrer">OIC · Tail Risk Video</a><a href="https://github.com/TauricResearch/TradingAgents" target="_blank" rel="noreferrer">TradingAgents · GitHub</a><small>K 线为教学构造样本，不冒充实时行情。使用真实交易前，必须重新获取带日期和时间的开盘价、最高价、最低价、收盘价和成交量（OHLCV）。</small></div>`;document.querySelector('footer').before(mastery);
const quantLab=document.createElement('section');quantLab.id='quantLab';quantLab.className='module tool-hidden';quantLab.innerHTML=`<div class="section-head"><div><span class="kicker">数据回测 · 组合压力</span><h2>赚多少之外，还要看跌过多少、换一组数据是否仍有效</h2></div><span class="tag">含成本 · 分样本</span></div><div class="quant-grid"><article><h3>趋势策略教学回测</h3><label>每次交易成本（bp）<input id="tradeCost" type="number" value="10"></label><label>数据区间<select id="sampleSet"><option value="train">训练样本</option><option value="test">未用于调整策略的数据（样本外）</option></select></label><button id="runBacktest">运行回测</button><div id="backtestResult" class="lab-output"></div><canvas id="equityChart" width="700" height="260"></canvas></article><article><h3>多资产压力测试</h3><p>股票 60%、长债 20%、短债 10%、现金 10%。</p><label>情景<select id="shock"><option value="inflation">通胀再起：股 -12%，长债 -10%</option><option value="recession">衰退：股 -20%，长债 +8%</option><option value="liquidity">流动性冲击：股 -18%，长债 -6%</option></select></label><button id="runAssets">运行组合压力</button><div id="assetResult" class="lab-output"></div></article></div>`;mastery.before(quantLab);
const train=[100,102,101,105,108,106,111,114,110,116,119,117,123],test=[100,98,101,97,95,99,96,103,101,100,106,104,108];runBacktest.onclick=()=>{const data=sampleSet.value==='train'?train:test,cost=+tradeCost.value/10000;let eq=100,peak=100,dd=0,trades=0,curve=[eq];for(let i=2;i<data.length;i++){if(data[i-1]>data[i-2]){eq*=1+(data[i]/data[i-1]-1)-cost;trades++}peak=Math.max(peak,eq);dd=Math.min(dd,eq/peak-1);curve.push(eq)}backtestResult.textContent=`净值 ${eq.toFixed(1)}；最大回撤 ${(dd*100).toFixed(1)}%；交易 ${trades} 次。${sampleSet.value==='test'?'这是样本外结果，仍不代表未来。':'训练样本好看不算过关，切到样本外再看。'}`;const c=equityChart,x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);x.beginPath();curve.forEach((v,i)=>{const px=25+i/(curve.length-1)*(c.width-50),py=c.height-25-(v-85)/40*(c.height-50);i?x.lineTo(px,py):x.moveTo(px,py)});x.strokeStyle='#3b8b61';x.lineWidth=3;x.stroke()};runAssets.onclick=()=>{const losses={inflation:-.092,recession:-.104,liquidity:-.12},r=losses[shock.value];assetResult.textContent=`组合压力损失约 ${(r*100).toFixed(1)}%。若账户熔断线为 8%，本情景全部触发：停止增加风险，检查是否需要调整各类持仓比例、增加备用现金。`};
calcBond.onclick=()=>{const change=-(+duration.value)*(+bps.value/100);bondResult.textContent=`价格近似变化 ${change.toFixed(2)}%。这是线性近似，利率大幅变动时还要考虑价格曲线的弯曲程度（凸性）。`};
document.querySelectorAll('.mini-quiz button').forEach((b,i)=>b.onclick=()=>{const ok=i===2;b.parentElement.querySelectorAll('button').forEach((x,n)=>x.className=n===2?'correct':n===i?'wrong':'');b.parentElement.nextElementSibling.textContent=ok?'通过：Vega 约 -$2.40，Theta 约 -$0.08，总计约 -$2.48。':'未通过：方向不变不代表期权价格不变；计算 Vega 与 Theta。'});
runAgents.onclick=()=>{const age=agentTime.value?(Date.now()-new Date(agentTime.value).getTime())/36e5:9999;let reasons=[];if(age>24)reasons.push('数据超过24小时或没填数据时间');if(bullCase.value.trim().length<20)reasons.push('请用至少 20 个字说明为什么可能上涨');if(bearCase.value.trim().length<20)reasons.push('请用至少 20 个字说明为什么可能判断错');if(+maxLoss.value<=0)reasons.push('未声明最大损失');if(invalidCase.value.trim().length<15)reasons.push('请用至少 15 个字说明出现什么情况就放弃原判断');agentVerdict.textContent=reasons.length?`风险官拒绝：${reasons.join('；')}。`:`风险检查通过，可以继续模拟交易：run-${Date.now().toString(36)}。这不会提交真实订单。`};
const exam=[['K线','突破最可靠的组合？',['盘中刺穿','放量收盘站稳且回踩守住','社媒热度'],1],['仓位','同一类风险的三笔持仓同时下跌，应按什么管理？',['三笔独立机会','合起来看持仓金额和一起下跌的损失','只看最大盈利'],1],['宏观','美联储议息（FOMC）前最重要的准备？',['满仓猜方向','上涨、下跌、震荡三种预案与出现什么情况就放弃原判断','忽略 2 年期国债收益率'],1],['期权','买Call财报后方向对仍亏的常见原因？',['市场预估波动率回落（IV Crush）和时间流逝（Theta）','成交量颜色','股票代码'],0],['Agents','研究卡没写可能推翻判断的证据，风险检查该怎么做？',['继续下单','拒绝继续模拟交易','放大仓位'],1]];examQuestions.innerHTML=exam.map((q,i)=>`<fieldset><legend>${i+1}. ${q[0]}：${q[1]}</legend>${q[2].map((o,n)=>`<label><input type="radio" name="exam-${i}" value="${n}">${o}</label>`).join('')}</fieldset>`).join('');submitExam.onclick=()=>{let score=0,missing=0;exam.forEach((q,i)=>{const x=document.querySelector(`input[name="exam-${i}"]:checked`);if(!x)missing++;else if(+x.value===q[3])score++});if(missing){examResult.textContent=`还有 ${missing} 题未答。`;return}const pass=score>=4;examResult.textContent=`${score}/5 · ${pass?'结业验收通过。请继续用模拟交易记录至少 20 笔再评估真实行为。':'未通过。回到对应章节复习，不能用收益结果替代决策质量。'}`;localStorage.setItem('manga-us-final',pass?'pass':'review')};
