const SIM_KEY='manga-us-sim-v1';
const SIM_BARS=[[100,103,98,102,120],[102,105,100,104,135],[104,106,84,96.2,390],[96,99,92,94,260],[94,98,93,97,180],[97,101,96,100,150],[100,103,98,101,145],[101,102,96,97,210],[97,101,96,100,175],[100,103,99,102,190],[102,106,101,105.1,280],[105,108,104,107,240],[107,109,103,104,220],[104,106,101,102,205],[102,105,100,104,195],[104,107,103,106,210],[106,108,102,103,310],[103,105,99,100,330],[100,104,98,103,260],[103,112,102,110,420],[110,113,107,109,300],[109,111,105,106,290],[106,110,104,108,250],[108,112,107,111,370],[111,114,109,113,340],[113,115,110,112,280],[112,116,111,115,310],[115,118,113,117,360]];
const SIM_OUTCOMES={1:{kind:'buy',qty:190,price:100,text:'按 $800 风险预算和每股 $4.20 风险反推，建立 190 股 Paper 仓位。'},2:{kind:'mark',price:96.2,text:'假公告引发跳空。计划正确但交易仍亏损，未实现损失 $722。'},3:{kind:'sell',qty:190,price:96.2,text:'执行熔断退出，已实现 -$722；没有加倍追回。'},10:{kind:'buy',qty:200,price:102,text:'放量收盘并回踩后，限价成交 200 股。'},11:{kind:'sell',qty:200,price:105.1,text:'按计划退出，计入滑点后收益 $620。'},20:{kind:'option',cost:300,text:'买入 1 张定义风险 Call，权利金支出 $300。'},23:{kind:'expire',value:0,text:'事件后 IV 回落先压低合约价格；随后到期仍为价外，合约才归零。好流程也可能亏 $300。'}};
function freshSim(){return {schema:1,runId:'shan-'+Date.now().toString(36),symbol:'SHAN',barCursor:5,account:{cash:100000,equity:100000,realized:0,unrealized:0},positions:[],orders:[],history:[]}}
function readSim(){try{const x=JSON.parse(localStorage.getItem(SIM_KEY)),number=v=>Number.isFinite(v),position=p=>p&&typeof p.id==='string'&&typeof p.symbol==='string'&&['stock','option'].includes(p.kind)&&number(p.qty)&&number(p.avg)&&number(p.mark),order=o=>o&&Number.isInteger(o.chapter)&&['BUY','SELL'].includes(o.side)&&number(o.qty)&&number(o.price),history=h=>h&&Number.isInteger(h.chapter)&&typeof h.title==='string'&&number(h.equity)&&number(h.pnl)&&typeof h.text==='string'&&typeof h.time==='string';const valid=x&&x.schema===1&&typeof x.runId==='string'&&typeof x.symbol==='string'&&Number.isInteger(x.barCursor)&&x.barCursor>=0&&x.account&&['cash','equity','realized','unrealized'].every(k=>number(x.account[k]))&&Array.isArray(x.positions)&&x.positions.every(position)&&Array.isArray(x.orders)&&x.orders.every(order)&&Array.isArray(x.history)&&x.history.every(history);return valid?x:freshSim()}catch{return freshSim()}}
let sim=readSim();
function saveSim(){localStorage.setItem(SIM_KEY,JSON.stringify(sim))}
function applyOutcome(index){const event=SIM_OUTCOMES[index];if(!event)return {pnl:0,text:'本章更新了决策证据，没有强行制造一笔交易。'};if(event.kind==='buy'){const cost=event.qty*event.price;if(sim.account.cash<cost)return {pnl:0,text:'现金不足，订单被风险门拒绝。'};sim.account.cash-=cost;sim.positions=[{id:'shan-stock',symbol:'SHAN',kind:'stock',qty:event.qty,avg:event.price,mark:event.price}];sim.orders.push({chapter:index+1,side:'BUY',qty:event.qty,price:event.price})}if(event.kind==='mark'){const p=sim.positions.find(x=>x.kind==='stock');if(p)p.mark=event.price}if(event.kind==='sell'){const p=sim.positions.find(x=>x.kind==='stock');if(p){const proceeds=event.qty*event.price,pnl=(event.price-p.avg)*event.qty;sim.account.cash+=proceeds;sim.account.realized+=pnl;sim.positions=[];sim.orders.push({chapter:index+1,side:'SELL',qty:event.qty,price:event.price})}}if(event.kind==='option'){sim.account.cash-=event.cost;sim.positions.push({id:'shan-call',symbol:'SHAN',kind:'option',qty:1,multiplier:100,avg:event.cost,mark:event.cost})}if(event.kind==='expire'){const p=sim.positions.find(x=>x.kind==='option');if(p){sim.account.realized-=p.avg;sim.positions=sim.positions.filter(x=>x!==p)}}sim.barCursor=Math.max(sim.barCursor,index+1);sim.account.unrealized=sim.positions.reduce((n,p)=>n+(p.mark-p.avg)*(p.kind==='stock'?p.qty:1),0);sim.account.equity=sim.account.cash+sim.positions.reduce((n,p)=>n+p.mark*(p.kind==='stock'?p.qty:1),0);return {pnl:sim.account.equity-(sim.history.at(-1)?.equity||100000),text:event.text}}
const simBaseComplete=v2Complete;
v2Complete=function(ok,button){const existed=v2Done.has(v2Active);if(button)button.classList.add(ok?'answer-right':'answer-wrong');if(!ok){lessonFeedback.textContent='宁姚：风险门拒绝。 '+V2_WHY[v2Active]+' 你可以修改后再试。';return}lessonStage.querySelectorAll('[data-pick]').forEach(b=>b.disabled=true);if(existed){lessonFeedback.textContent='陈平安：本章已经记录，复习不会重复成交。';return}v2Done.add(v2Active);const result=applyOutcome(v2Active);sim.history.push({chapter:v2Active+1,title:V2_TITLES[v2Active][0],equity:sim.account.equity,pnl:result.pnl,text:result.text,time:new Date().toISOString()});v2Equity=sim.account.equity;v2Save();saveSim();lessonFeedback.textContent=result.text+' '+V2_WHY[v2Active];v2Rail();v2Journal()};
v2Chart=function(){const c=document.querySelector('#storyChart');if(!c)return;const rows=SIM_BARS.slice(0,Math.min(SIM_BARS.length,Math.max(5,sim.barCursor))),p=c.getContext('2d'),lo=Math.min(...rows.map(x=>x[2])),hi=Math.max(...rows.map(x=>x[1])),step=(c.width-80)/Math.max(rows.length,1),y=v=>210-(v-lo)/(hi-lo)*160;p.clearRect(0,0,c.width,c.height);rows.forEach((b,i)=>{const x=45+i*step;p.strokeStyle=b[3]>=b[0]?'#207a58':'#b95443';p.beginPath();p.moveTo(x,y(b[1]));p.lineTo(x,y(b[2]));p.stroke();p.fillStyle=p.strokeStyle;p.fillRect(x-5,y(Math.max(b[0],b[3])),10,Math.max(3,Math.abs(y(b[0])-y(b[3]))));p.globalAlpha=.3;p.fillRect(x-6,268-b[4]/6,12,b[4]/6);p.globalAlpha=1});p.fillStyle='#667673';p.fillText(`SHAN · D1-D${rows.length} · 固定教学 OHLCV`,18,20)};
const simBaseRender=v2Render;
v2Render=function(){simBaseRender();const stage=v2Stage(v2Active),lines=[['陈平安','先记当时看得见的事实。'],['阿良',stage<2?'这走势，不梭哈都对不起它。':'要不先赌一把，理由收盘后再补？'],['宁姚','没有最大损失和失效条件，不放行。'],['周米粒','先想摔下山会断几根骨头，再看山顶风景。']];const strip=document.createElement('div');strip.className='story-thread';strip.innerHTML=`<b>山河科技 ETF · 第 ${stage+1} 幕</b>`+lines.map((x,i)=>`<p><img src="assets/chat-avatars/${['陈平安-7900ed1ee3359c71.png','阿良-c7de86724bd40304.png','宁姚-1ca9c3a0b6ec2dc9.png','周米粒-61ad07e7e0a1025b.png'][i]}" alt="${x[0]}"><span><b>${x[0]}</b>${x[1]}</span></p>`).join('');lessonStage.querySelector('.comic-strip').replaceWith(strip);v2Chart()};
const simBaseJournal=v2Journal;
v2Journal=function(){simBaseJournal();tradeJournal.querySelector(':scope > b').textContent='$'+sim.account.equity.toLocaleString();const state=document.createElement('div');state.className='account-state';state.innerHTML=`<span>现金 <b>$${sim.account.cash.toLocaleString()}</b></span><span>已实现 <b>${sim.account.realized>=0?'+':''}$${sim.account.realized.toLocaleString()}</b></span><span>未实现 <b>${sim.account.unrealized>=0?'+':''}$${sim.account.unrealized.toLocaleString()}</b></span><span>持仓 <b>${sim.positions.length}</b></span>`;tradeJournal.querySelector('.proof').before(state);const journal=tradeJournal.querySelector('.journal-events');if(journal)journal.innerHTML='<b>最近决策</b>'+sim.history.slice(-4).reverse().map(e=>`<span>第${e.chapter}章 · ${e.title}<small>${e.pnl>=0?'+':''}$${e.pnl}</small></span>`).join('')};
document.querySelector('nav').innerHTML='<a href="#trainingDesk">训练台</a><a href="#trainingDesk">Paper 账户</a><a href="#trainingDesk">28 章路线</a>';
document.querySelector('.brand small').textContent='SHAN 连续交易训练';
v2Render();
