const {chromium}=require('playwright');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,channel:'chrome'});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:4186/#delta-gamma');
const term=page.locator('.dialogue .term-link').filter({hasText:/^Delta$/}).first();await term.hover();await page.locator('#termPanel').waitFor({state:'visible'});assert.match(await page.locator('#termPanel').textContent(),/什么意思/);await term.click();await page.mouse.move(0,0);assert.equal(await page.locator('#termPanel').isVisible(),true);await page.keyboard.press('Escape');assert.equal(await page.locator('#termPanel').isVisible(),false);assert.equal(await term.evaluate(e=>e===document.activeElement),true);
await page.goto('http://127.0.0.1:4186/#risk-gate');
const option=page.locator('.option .term-link').first();await option.click();assert.equal(await page.locator('input[name=answer]:checked').count(),0);await page.keyboard.press('Escape');
await page.locator('#glossaryOpen').click();await page.locator('#termSearch').fill('Delta');assert.ok(await page.locator('.dictionary-entry').count()>0);await page.locator('.dictionary-entry').first().click();assert.match(await page.locator('#termPanel').textContent(),/容易误解/);await page.getByRole('button',{name:'← 返回词典'}).click();await page.locator('#termSearch').fill('不存在xyz');assert.match(await page.locator('#termResults').textContent(),/没有找到/);await page.keyboard.press('Escape');
await page.evaluate(()=>{window.LearningTerms.enhance(document.querySelector('#lesson'));window.LearningTerms.enhance(document.querySelector('#lesson'));});assert.equal(await page.locator('.term-link .term-link').count(),0);
await page.locator('#glossaryOpen').click();await page.locator('#termSearch').fill('Call');await page.locator('.dictionary-entry').first().click();await page.screenshot({path:'output/playwright/terms-desktop.png'});await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);const box=await page.locator('#termPanel').boundingBox();assert.ok(box.x>=0&&box.x+box.width<=390&&box.y>=0);await page.screenshot({path:'output/playwright/terms-mobile.png'});
await page.locator('.term-close').click();await page.locator('#glossaryOpen').click();await page.locator('#termSearch').fill('波动');assert.ok(await page.locator('.dictionary-entry').count()>0);assert.deepEqual(errors,[]);await browser.close();console.log('PASS terms: hover, click pin, Escape/focus, quiz safety, dictionary search/back/empty, idempotent decoration, mobile bounds.');})().catch(e=>{console.error(e);process.exit(1)});
